name: Deploy docs

jobs:
  buid-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version : 16

      - name: Set OpenSSL legacy provider
        run: |
          NODE_OPTIONS="--openssl-legacy-provider"

      - run: npm ci

      - run: npm run build

      - name: Deploy storybook
        working-directory: ./packages/docs
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - master